spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: false

  security:
    user:
      name: user
      password: password

  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      format_sql: true
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always